version: '3.1'

services:

  connectDBapp:
    container_name: docker-node-mongo
    restart: always
    ports:
      - 80:3000
    links:
      - mongo
  
  
  
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - '27017:27017'

  